name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v4

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.PAC}}

          - name: 'Build Image'
            run: |
              docker build . --tag ghcr.io/feuerhamster/jetlag-br-bot:latest
              docker push ghcr.io/feuerhamster/jetlag-br-bot:latest
